# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
encoding: utf-8
title: Дизайн интерьера и Архитектурное проектирование в Санкт-Петербурге и Самаре от студии дизайна WRIGHT FORM
name: WrightForm
email: office@wrfrm.com
description: 'У нас вы можете ознакомиться с портфолио и заказазать: Дизайна интерьера, Ремонт под ключ, Архитектурное проектирование и Декорирование'
keywords: дизайн интерьера, студия дизайна, студия дизайна интерьера, ремонт под ключ, архитектурный проект, декорирование, wrightform, райтформ, самара, Санкт-Петербург, СПБ

themecolor: '#333'
imagehome: img/header-img.jpg
url: 'https://wrfrm.com'
baseurl: '/' # the subpath of your site, e.g. /blog

# plugins: [jekyll-paginate-v2]
# category_dir: portfolio
# pagination:
#   enable: true 
#   per_page: 100
#   title: ':title - Страница :num'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true
#   trail: 
#     before: 2
#     after: 2

exclude: ['node_modules', 'gulpfile.js', 'package.json', 'package-lock.json', js/common.js, 'npm-debug.log', '**/Thumbs.db', 'libs', 'sass', '**/*.DS_Store']


soc:
  <a class="social-link-circle-light" href="https://vk.com/wrightform" rel="nofollow" target="_blank">
    <span class="fa fa-vk"></span>
  </a>
  <a class="social-link-circle-light social-link-instagram" href="https://www.instagram.com/wrightform_architect/" rel="nofollow" target="_blank">
    <span class="fa fa-instagram"></span>
  </a>

vk: https://vk.com/wrightform
instagram: https://www.instagram.com/wrightform_architect/
facebook: https://www.facebook.com/wrfrm/

copyright: Копирование контента и размещение на других сайтах запрещено.

telephone: +7 917 118-02-70
telephone-second: +7 927 746-01-11
phone-href: 'tel:+79171180270'
phone-second-href: 'tel:+79277460111'

price-interior: 1900 р/м2
price-interior-full: 2200 р/м2
price-interior-commerce: 1200 р/м2
price-interior-commerce-full: 1500 р/м2
price-architecture: 1800 р/м2
pice-build: от 12<sup> </sup>000 р/м2
price-visualisation: 700 р/м2
price-supervision: 28<sup> </sup>000 р/мес
price-consultation: 9<sup> </sup>000 р
price-decor: 1000 р/м2

url-interior: uslugi/dizajn-interera/
url-interior-commerce: uslugi/dizajn-interera-kommercheskij/
url-architecture: uslugi/arkhitekturnyj-proekt/
url-build: uslugi/remont-pod-klyuch/
url-visualisation: uslugi/3d-vizualizaciya/
url-supervision: uslugi/avtorskij-nadzor/
url-consultation: uslugi/konsultaciya/
url-decor: uslugi/dekorirovanie/

image-interior: images/dizajn-interera/2018-06-29-kvartira-dvukhkomnatnaya-72-kv-m-zhk-favorit/1.jpg
image-interior-commerce: images/dizajn-interera/2018-08-07-salon-krasoty-volgar/1.jpg
image-architecture: img/main/2-arkhitekturnyj-proekt.jpg
image-build: img/main/4-remont-pod-klyuch.jpg
image-visualisation: img/main/6-dizajn-interera.jpg
image-supervision: img/main/7-avtorskij-nadzor.jpg
image-consultation: img/main/8.jpg
image-decor: img/main/3-dekorirovanie.jpg

txt-payment-for-travel-outside: В случае нахождения объекта за пределами КАД действует система доплаты за выезд.

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
jivosite-widget: '<script src="//code-ru1.jivosite.com/widget.js" jv-id="uHADwec4Ko" async></script>'

yandex-dialog-widget: "<script type='text/javascript'>
(function () {
    window['yandexChatWidgetCallback'] = function() {
        try {
            window.yandexChatWidget = new Ya.ChatWidget({
                guid: '13deb08e-3a96-4722-8b80-6b136e807eec',
                buttonText: 'Напишите нам, мы онлайн!',
                title: 'Чат',
                theme: 'dark',
                collapsedDesktop: 'hover',
                collapsedTouch: 'always'
            });
        } catch(e) { }
    };
    var n = document.getElementsByTagName('script')[0],
        s = document.createElement('script');
    s.async = true;
    s.src = 'https://chat.s3.yandex.net/widget.js';
    n.parentNode.insertBefore(s, n);
})();
</script>"